---
comm_addr: "tcp://127.0.0.1:10000"
role: "customer"
part_id: "2000"
use_lora: false
peft_lora_config:
  r: 16
  lora_alpha: 32
  lora_dropout: 0
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
  # - "o_proj"
  # - "up_proj"
  # - "gate_proj"
  # - "down_proj"
  layers_to_transform: "range(0, 32)" # [15, 31] [19, 39] [29, 59] list(range(0, 32)) None
learning_rate: 0.005
model_type: "sap"
num_train_epochs: 1
train_dataset_name_or_paths:
  super_glue-boolq: "@tjasad/Slovene_SuperGLUE_BoolQ"    # Downloading form the internet if starts with @.
data_collator: "qlora"
per_device_eval_batch_size: 32
eval_tasks: "boolq"
evaluation_strategy: "no"
eval_steps: 2
do_init_eval: true
do_train: true
do_eval: false
overwrite_output_dir: true
bf16: true
report_to: "tensorboard"
save_strategy: "no"
gradient_checkpointing: false
per_device_train_batch_size: 8
gradient_accumulation_steps: 32
source_max_len: 900
logging_steps: 1
disable_tqdm: false
remove_unused_columns: false
train_on_source: false
warmup_steps: 20
output_dir: "../../../output"
use_cpu: true
